#
---
  - name: "Install cri-o on all nodes for: {{ project_tag }}"
    hosts: "role_{{ project_tag }}_node"
    roles:
    - role: crio
      become: yes

  - name: "Install desired things for Crane hacking"
    hosts: "role_{{ project_tag }}_node"
    roles:
    - role: case_watcher
      # intended to run as 'centos' user, so no on 'become'
      become: no 

  
